### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Shahxad-Akram** [electricbookworks/mini-mathjax#1]
mini-mathjax is not rendering the tex offline.. Is it possible to show it with an example?

**Comment by arthurattwell** [comment]
@shahxadakram You probably need to add a MathJax configuration to your page. Sorry I didn't mention that in the README. I've added a note on that now to the README, and a demo page here as an example: https://electricbookworks.github.io/mini-mathjax/

**Comment by Shahxad-Akram** [comment]
thanks, now its working like charm. thanks..
